#!/usr/bin/env python3
"""
Compose Helper - Docker Compose Service Block Generator
========================================================

Generates a ready-to-paste docker-compose service block for a new actuator.
Preserves human governance by requiring manual review before integration.

Usage:
    python compose_helper.py --name legal_compliance --port 5011
"""

import argparse


def generate_compose_block(name: str, port: int, network: str = "inner-mesh"):
    """Generate a docker-compose service block for an actuator."""

    block = f"""
# =============================================================================
# SERVICE BLOCK FOR: {name}
# Generated by actuator-gen/compose_helper.py
# =============================================================================
  {name}:
    build:
      context: ../services/{name}
      dockerfile: Dockerfile
    ports:
      - "{port}:{port}"
    environment:
      - ACTUATOR_REGISTRY_URL=http://actuator_registry:5100
      - LEDGER_URL=http://ledger_service:8082
      - EVIDENCE_URL=http://evidence_writer:8080/log
    depends_on:
      - ledger_service
      - evidence_writer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{port}/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - {network}
    labels:
      mission.role: "actuator"
      mission.capability: "{name}"
      mission.killable: "true"
# =============================================================================
# END OF BLOCK FOR: {name}
# =============================================================================
"""

    print(block)
    print("\n" + "=" * 70)
    print("INSTRUCTIONS")
    print("=" * 70)
    print(f"""
1. Copy the YAML block above (between the comment markers)

2. Paste it into the 'services' section of your docker-compose file:
   - compose/docker-compose.mission.yml (for mission stack)
   - docker-compose.runtime.yml (for runtime stack)

3. Verify the following before deployment:
   - Port {port} is not already in use by another service
   - The network '{network}' matches your compose file's network name
   - The service name '{name}' is unique

4. Deploy with:
   docker compose -f <your-compose-file>.yml up -d --build {name}

5. Verify registration:
   curl http://localhost:5100/actuators | jq '.[] | select(.name=="{name}")'
""")


def main():
    parser = argparse.ArgumentParser(
        description="Generate a docker-compose service block for an actuator"
    )
    parser.add_argument(
        '--name',
        required=True,
        help='Snake_case name of the actuator'
    )
    parser.add_argument(
        '--port',
        type=int,
        default=5007,
        help='Port for the actuator service (default: 5007)'
    )
    parser.add_argument(
        '--network',
        default='inner-mesh',
        help='Docker network name (default: inner-mesh)'
    )

    args = parser.parse_args()

    generate_compose_block(
        name=args.name,
        port=args.port,
        network=args.network
    )


if __name__ == '__main__':
    main()
