import React from 'react';
import Head from 'next/head';
import { motion } from 'framer-motion';
import { Shield, Search, FileCheck, AlertCircle, ExternalLink, Hash } from 'lucide-react';

export default function Verification() {
  const artefacts = [
    { path: 'CANON/TRINITY_DEPLOYMENT_PROTOCOL.md', status: 'MISSING', hash: 'N/A' },
    { path: 'CONSTITUTION.md', status: 'VERIFIED', hash: 'e89f00063c87be5c3f961a29f4f269f64457314d54e...' },
    { path: 'governance/THE_DIAMOND_DOCTRINE.md', status: 'VERIFIED', hash: 'a1b2c3d4e5f6g7h8i9j0...' },
    { path: 'SOP_DAILY.md', status: 'VERIFIED', hash: 'd064e71fa47d905f9ca616ce8e7a9e98998b703b...' }
  ];

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white selection:bg-white/10 selection:text-white">
      <Head>
        <title>Verification Index | Sovereign Systems</title>
      </Head>

      <nav className="fixed top-0 w-full z-50 border-b border-white/5 bg-[#0a0a0a]/80 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <a href="/" className="flex items-center gap-2 group cursor-pointer">
            <Shield className="w-6 h-6 text-white group-hover:scale-110 transition-transform" />
            <span className="font-bold tracking-tighter text-lg uppercase">Sovereign <span className="text-white/40">Systems</span></span>
          </a>
          <div className="hidden md:flex items-center gap-8">
            <a href="/" className="text-sm font-medium text-white/40 hover:text-white transition-colors tracking-tight">Home</a>
            <a href="/doctrine" className="text-sm font-medium text-white/40 hover:text-white transition-colors tracking-tight">Doctrine</a>
          </div>
        </div>
      </nav>

      <main className="pt-32 pb-20 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="mb-16">
            <h1 className="text-4xl font-black tracking-tighter mb-4 uppercase">Verification Index</h1>
            <p className="text-white/40 max-w-2xl font-light leading-relaxed">
              Live evidence ledger for all doctrinal artefacts. This index is generated by the Forensic Scanner agent and validated against the Merkle root.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
            <div className="lg:col-span-2 space-y-4">
              <div className="flex items-center justify-between px-6 py-4 border-b border-white/5 text-[10px] font-bold tracking-[0.2em] text-white/20 uppercase">
                <span>Artefact Path</span>
                <div className="flex gap-20">
                  <span>Status</span>
                  <span className="w-48">SHA-256 Hash</span>
                </div>
              </div>

              {artefacts.map((art, idx) => (
                <motion.div 
                  key={art.path}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: idx * 0.05 }}
                  className="group flex items-center justify-between px-6 py-5 rounded-xl border border-white/5 bg-white/[0.01] hover:bg-white/[0.03] transition-all"
                >
                  <div className="flex items-center gap-4">
                    <FileCheck className={`w-5 h-5 ${art.status === 'VERIFIED' ? 'text-emerald-400/40' : 'text-rose-400/40'}`} />
                    <span className="text-sm font-mono text-white/80">{art.path}</span>
                  </div>
                  <div className="flex items-center gap-8">
                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded border ${art.status === 'VERIFIED' ? 'border-emerald-400/20 text-emerald-400 bg-emerald-400/5' : 'border-rose-400/20 text-rose-400 bg-rose-400/5'}`}>
                      {art.status}
                    </span>
                    <span className="text-xs font-mono text-white/20 group-hover:text-white/40 transition-colors w-48 truncate">
                      {art.hash}
                    </span>
                    <ExternalLink className="w-4 h-4 text-white/10 group-hover:text-white/40 cursor-pointer" />
                  </div>
                </motion.div>
              ))}
            </div>

            <div className="space-y-8">
              <div className="p-8 rounded-3xl border border-white/10 bg-white/[0.02]">
                <h3 className="text-sm font-bold tracking-[0.2em] text-white/40 uppercase mb-6 flex items-center gap-2">
                  <AlertCircle className="w-4 h-4" /> Audit Gaps
                </h3>
                <div className="space-y-6">
                  <GapItem 
                    area="Core Protocol" 
                    title="TRINITY_DEPLOYMENT_PROTOCOL.md" 
                    impact="Unable to verify physical deployment invariants." 
                  />
                  <GapItem 
                    area="Operational Security" 
                    title="Transient scripts found" 
                    impact="Potential unauthorized code execution path." 
                  />
                </div>
              </div>

              <div className="p-8 rounded-3xl border border-emerald-400/10 bg-emerald-400/[0.02] border-dashed">
                <h3 className="text-sm font-bold tracking-[0.2em] text-emerald-400/60 uppercase mb-4">Merkle Root Seal</h3>
                <div className="font-mono text-[10px] break-all text-white/40 leading-relaxed">
                  b070db1d394cc775be2aab3dfacf7a1a09e2907d51ab0c3908668f39c89a2836
                </div>
                <div className="mt-4 flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-emerald-400" />
                  <span className="text-[10px] font-bold text-emerald-400/80 uppercase">Chain Integrity Verified</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

function GapItem({ area, title, impact }) {
  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between">
        <span className="text-[10px] font-bold text-rose-400/60 uppercase">{area}</span>
        <span className="text-[10px] font-mono text-white/20">SIGNAL: RED</span>
      </div>
      <div className="text-sm font-bold text-white/80">{title}</div>
      <p className="text-xs text-white/40 leading-relaxed">{impact}</p>
    </div>
  );
}
